### PR TITLE
Update Anaconda's steering council members

### PR DESCRIPTION
**Pull request by jezdez**
Refs #58.

### CODE REVIEW

**Review by awwad — APPROVED** [review]

**Review by beckermr — APPROVED** [review]

**Comment by beckermr** [comment]
We need approval from @csoja and then we can merge.

**Review by csoja — APPROVED** [review]

**Review by chenghlee — APPROVED** [review]

**Comment by jezdez** [comment]
@cjmartian is out on PTO till August 1st FWIW.

**Comment by beckermr** [comment]
We need his consent before moving him to emeritus.

**Review by cjmartian — APPROVED** [review]

**Comment by jezdez** [comment]
Thank you @cjmartian!

**Pull request merged**
