### PR TITLE
Add Jaime to steering.csv

### PR DESCRIPTION
**Pull request by jaimergp**
I'd like to apply for membership!

About me:

* Jaime Rodríguez-Guerra, born in Spain
* Invested in the conda ecosystem ever since it saved my PhD research with package management issues
* Part of conda-forge core
* Worked on the libmamba integrations for conda
* Worked on the constructor stack, including a menuinst rewrite

### CODE REVIEW

**Comment by beckermr** [comment]
Awesome! I can setup a vote next week

**Comment by jaimergp** [comment]
May I send a gentle reminder @beckermr? :D

**Comment by beckermr** [comment]
I am so sorry. Let me do this now while the kids are sleeping.

**Comment by jaimergp** [comment]
Thank you so much! <3

**Comment by ocefpaf** [comment]
> done and my apologies again!

Did you use adoodle? I usually get their emails without a problem but I did not get anything this time.

**Comment by beckermr** [comment]
I did. Anything in spam?

**Comment by beckermr** [comment]
I double-checked on my side and you were sent an email. Let me see if I can send it again.

**Comment by beckermr** [comment]
OK try again. It said it sent you something.

**Comment by goanpeca** [comment]
Hmmm I don'y think I got the email @beckermr 🤔

**Comment by beckermr** [comment]
It was sent to goanpeca@gmail.com. Please check spam and I can resend.

**Comment by goanpeca** [comment]
Got and voted, thanks @beckermr :)

**Comment by jaimergp** [comment]
@beckermr Is this PR enough to add myself to the team?

**Comment by beckermr** [comment]
I'll do that by hand. Merging!

**Comment by jezdez** [comment]
Welcome @jaimergp!!

**Comment by jaimergp** [comment]
Thanks everyone!

**Pull request merged**
