### PR TITLE
add missing meeting notes

### PR DESCRIPTION
**Pull request by jaimergp**
There was a gap in the archived meeting notes, so I browsed the Slack server for hackmd.io links.  This is all I found, which leaves the `archive` like this:

```
20200721_agenda_and_minutes.md
20200824_agenda_and_minutes.md
20200908_agenda_and_minutes.md
20200922_agenda_and_minutes.md
20201006_agenda_and_minutes.md
20201020_agenda_and_minutes.md
20201102_agenda_and_minutes.md
20201117_agenda_and_minutes.md
20201201_agenda_and_minutes.md
20201215_agenda_and_minutes.md
20210112_agenda_and_minutes.md
20210126_agenda_and_minutes.md
20210303_agenda_and_minutes.md
20210317_agenda_and_minutes.md
20210331_agenda_and_minutes.md
20210414_agenda_and_minutes.md
20210428_agenda_and_minutes.md
20210511_agenda_and_minutes.md
20210525_agenda_and_minutes.md
20210623_agenda_and_minutes.md
20210707_agenda_and_minutes.md
20210721_agenda_and_minutes.md
```

I can see there're some (expected) dates missing, but I don't know if the meeting didn't happen then or no notes were taken:

* 2021 February had no meetings
* 2021 June had only one meeting, but I think one of them was canceled because it conflicted with Anaconda Con?

### CODE REVIEW

**Comment by beckermr** [comment]
Thank you for doing this!

We have some meeting notes here as well: https://hackmd.io/team/conda-community?nav=overview

**Comment by beckermr** [comment]
It looks like we got some of those. Let's merge this and then I'll double check.

**Comment by chenghlee** [comment]
@jaimergp: looking back at my calendar, I can confirm that there were no meetings in Feb 2021, and the 9 Jun 2021 meeting was cancelled due to AnacondaCON.

**Comment by beckermr** [comment]
I double-checked and we have everything from the hackmd team.

**Comment by jaimergp** [comment]
Excellent! Thanks everybody!

**Pull request merged**
